services:
  - type: web
    name: faq-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chatbot_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true 